MAXIMUM_INSTANTANEOUS_POWER__W = 4_000.
MAXIMUM_15MIN_POWER__W = 900.

AMBIENT_TEMPERATURE__degC = 20.
INCOMING_WATER_TEMPERATURE__degC = 10.
SPECIFIC_HEAT_CAPACITY__J_per_kg_degC = 4_184.
WATER_DENSITY__kg_per_m3 = 1000.
TIME_STEP__sec = 60