# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests and Linter

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Creating virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        source .venv/bin/activate

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        python -m poetry install
        
    - name: Lint with flake8
      run: |
        python -m poetry run python -m flake8 .

    - name: Run tests
      run: |
        python -m poetry run python -m pytest ./tests
